name: 'iOS Test Action'
descrption: 'OWOW iOS Test action'
inputs:
  scheme:
    description: 'The Xcode scheme to build'
    required: true
  workspace:
    description: 'The Xcode workspace to use when building. When not set, no workspace parameter is passed to xcodebuild.'
    required: false
  destination:
    description: 'The build destination passed to xcodebuild.'
    required: false
    default: 'name=iPhone 13,OS=15.0'
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Mint bootstrap
      shell: bash
      run: |
        # This first step makes sure only one instance of mint is running at the same time.
        # If more than one instance is running, it will wait until it is finished before proceeding.
        arch -arm64 lsof -p $(pgrep mint) +r 1 &>/dev/null || true
        
        # The mint bootstrap step makes sure we use the swiftlint version that is declared in the project.
        arch -arm64 mint bootstrap
    - name: Pod Install
      shell: bash
      run: |
        if [[ -f Podfile ]]; then
          arch -arm64 pod install
        else
          echo No Podfile found - nothing to do
        fi
    - name: Build & test
      shell: bash
      run: ${{ github.action_path }}/test.sh

